baseURL = "https://miguelsimoni.github.io/hugo-initio-site/"
languageCode = "en-us"
publishDir = "docs"
theme = "hugo-initio"
title = "Initio - Free, multipurpose html5 template by GetTemplate"
[[menu.main]]
name = "home"
url = "/"
weight = 1
[[menu.main]]
name = "blog"
url = "/post/"
weight = 5
[params]
DateForm = "January 2, 2006"
address = "123 A Road To Nowhere, The Best City, State 54321"
background = ""
description = "A very frustrated noon dev"
email = "example@exampleemail.com"
favicon = "images/gt_favicon.png"
footerEnableContact = true
footerEnableFollowme = true
footerEnableFormWidget = true
footerEnableTextWidget = true
name = "Alexander Rivera"
phone = "123 456 7890"
showClients = true
showDownload = true
showRecentWorks = true
showServices = true
showSubheader = true
year = "2018"
[params.disqus]
site = "hugo-initio-site.disqus.com"
[params.google.analytics]
trackerID = "GA-000000000-0"
[params.sharethis]
custom = true
property = "123456789012345678901234"
[[params.social]]
footer = true
icon = "fa-facebook-square"
network = "facebook"
sharethis = true
title = "facebook"
url = "https://www.facebook.com/nickname"
[[params.social]]
footer = true
icon = "fa-twitter-square"
network = "twitter"
sharethis = true
title = "twitter"
url = "https://twitter.com/nickname"
[[params.social]]
footer = true
icon = "fa-instagram"
network = ""
sharethis = false
title = "instagram"
url = "https://www.instagram.com/nickname"
[[params.social]]
footer = false
icon = "fa-google-plus-square"
network = "googleplus"
sharethis = true
title = "google+"
url = "https://plus.google.com/+nickname"
[[params.social]]
footer = false
icon = "fa-linkedin-square"
network = "linkedin"
sharethis = true
title = "linkedin"
url = "https://www.linkedin.com/in/nickname"
[[params.social]]
footer = false
icon = "fa-tumblr-square"
network = "tumblr"
sharethis = false
title = "tumblr"
url = "https://nickname.tumblr.com"
[[params.social]]
footer = true
icon = "fa-github"
network = ""
sharethis = false
title = "github"
url = "https://github.com/nickname"
[[params.social]]
footer = false
icon = "fa-envelope"
network = "email"
sharethis = true
title = "email"
url = "mailto:some.email@somewhere.com"
